### ISSUE TITLE
RSS-syöte ei toimi

### ISSUE THREAD

**Issue by Tomin1** [viikonvalo/viikonvalo.fi#11]
Viikon VALOn RSS-syöte ei toimi. Sivuilla on linkki http://viikonvalo.fi/rss.xml mutta se ei lataudu.

**Comment by tikank** [comment]
RSS-syötteessä oli pitkään jotain vikaa. Joko sen lataus kesti tolkuttoman kauan tai sitten sitä ei saanut ladattua ollenkaan. 

Huomasin, että joskus viikko tai pari sitten syöte alkoi toimia, ja nyt ainakin minulla sen lataaminen onnistuu. 

Olisikohan tämä juttu nyt korjattu?

**Comment by pesasa** [comment]
Vika tuli ilmeisesti siinä vaiheessa, kun vaihdoin sivuston alustaksi Phile:n. Markdown-tiedostoja käyttävä tietokannaton Phile on ihan näppärä alusta pienille sivustoille, mutta kävi ilmi, että sen toiminta näytti olevan sittenkin liian raskasta, kun sivustolla on sivustoja yli 250 kappaletta. RSS-feedistä tuli liian raskas.

Pari viikkoa sitten vaihdoin sivustolla käytettäväksi järjestelmäksi myöskin Markdownia käyttävän Hugon. Hugo ei luo sivuja lennossa vaan sillä generoidaan etukäteen valmiit staattiset sivut. Tämän ansiosta Viikon VALO muuttui salaman nopeaksi.

Eli kyllä, RSS-ongelma korjautui tuolla. RSS:n urliksi tosin vaihtui http://viikonvalo.fi/index.xml , mutta koetan pitää tuon vanhan urlin myös toiminnassa.
