### ISSUE TITLE
Linkkejä valosta valoon rikki

### ISSUE THREAD

**Issue by tikank** [viikonvalo/viikonvalo.fi#16]
Näyttäisi siltä, että linkit valo-artikkeleista toisiin valo-artikkeleihin on rikki. 

Esim. 
http://viikonvalo.fi/Onlyoffice/ --> http://viikonvalo.fi/Onlyoffice/OwnCloud
http://viikonvalo.fi/LibreOffice_5/ --> http://viikonvalo.fi/LibreOffice_5/Calligra_Suite
http://viikonvalo.fi/Open_Science/ --> http://viikonvalo.fi/Open_Science/Python

Liekö sivujen generoinnissa (millä se sitten onkaan tehty) muuttunut jotain niin, että linkit tulevat sivuille väärin, koska itse artikkeleita ei ole näköjään muutettu.

**Comment by pesasa** [comment]
Kappas. Kiitos hyvästä huomiosta. Täytyy korjata.

Siirsin sivuston juuri Hugo:lla generoiduksi ja sisäiset linkit näköjään vaativat pientä säätöä.
Hugossa jokainen sivu on omassa hakemistossaan, joten suhteellinen linkitys ei toimi ihan samoin kuin edellisellä alustalla.

**Comment by pesasa** [comment]
Sisäiset linkitykset korjattu.
