### ISSUE TITLE
Rikkinäisiä linkkejä

### ISSUE THREAD

**Issue by tikank** [viikonvalo/viikonvalo.fi#17]
Huomasin muutaman rikkinäisen linkin Viikon valosta:

Sivupalkissa 
- FLOSS Manuals --> http://fi.flossmanuals.net/ ei taida enää olla olemassa.
- Jaa jotain -päivä http://viikonvalo.fi/Jaa_jotain ei löydy

Kysymys/vastaus-sivulla http://viikonvalo.fi/vastaukset/ punatulkun kuva ei näy.

**Comment by pesasa** [comment]
Kiitoksia taas huomioista.

Suomenkielinen FLOSS Manuals on tosiaan lopettanut. Päivitin sivua ja linkkejä viittaamaan englanninkieliseen sivustoon sekä kansainvälisen sivuston kautta löytyviin suomenkielisiinkin materiaaleihin.

Jaa jotain -päivän linkki myös päivitetty ja FAQ-sivun kuvalinkit.
